name: CMake Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install CURL
      run: |
        sudo apt update
        sudo apt -y install curl
        sudo apt-get install libcurl4-openssl-dev
    
    - name: Install cJSON
      run: |
        cd ~
        git clone https://github.com/DaveGamble/cJSON
        cd cJSON
        mkdir build
        cd build
        cmake ..
        sudo make install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#    - name: Test
#      working-directory: ${{github.workspace}}/build
#      run: ctest -C ${{env.BUILD_TYPE}}
      
