name: 'Docs'

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libclang-cpp1-9 libclang1-9

      # Generate documentaiton in docs/html folder
      - name: Generate Doxygen Documentation
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          working-directory: .
      
      # Create .nojekyll file
      #- name: Create .nojekyll
      #  run: touch docs/html/.nojekyll
      #  shell: bash
      
      # Deploy using GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: docs/html
